sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t anitbibin/app-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true anitbibin/app-docker-react npm run test