sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t anitbibin/app-docker-react -f Dockerfile.dev .

script:
    - docker run anitbibin/app-docker-react

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "app-docker-react"
    env: "AppDockerReact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-119817990495"
    bucket_path: "app-docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
